var should = require('should')
var ipci = require('../')

describe('basic', function () {
  it('should return Travis CI when given a single Travis CI .com IP', function (done) {
    var result = ipci('54.172.141.90')
    should.exist(result)
    should(result).equal('Travis CI')
    should(result).not.equal('Travis')
    should(result).not.equal('Wercker CI')
    should(result).not.equal('CircleCI')
    should(result).not.equal('54.172.141.90')
    done()
  })
  it('should return Travis CI when given a single Travis CI .org IP', function (done) {
    var result = ipci('52.0.240.122')
    should.exist(result)
    should(result).equal('Travis CI')
    should(result).not.equal('Travis')
    should(result).not.equal('Wercker CI')
    should(result).not.equal('CircleCI')
    should(result).not.equal('52.0.240.122')
    done()
  })
  it('should return Wercker when given a single Wercker IP', function (done) {
    var result = ipci('54.175.201.227')
    should.exist(result)
    should(result).equal('Wercker')
    should(result).not.equal('Wercker CI')
    should(result).not.equal('Travis CI')
    should(result).not.equal('CircleCI')
    should(result).not.equal('54.175.201.227')
    done()
  })
  it('should return the IP when it doesn’t match a CI service', function (done) {
    var result = ipci('216.202.261.151')
    should.exist(result)
    should(result).equal('216.202.261.151')
    should(result).not.equal('Travis CI')
    should(result).not.equal('Wercker CI')
    should(result).not.equal('Travis CI')
    should(result).not.equal('CircleCI')
    done()
  })
})
